# Generated by Django 2.2.7 on 2019-11-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('article_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('article_last_updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号码')),
                ('intro', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='个人博客地址')),
                ('uinfo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('comment_content', models.CharField(max_length=400, verbose_name='评论内容')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Article', verbose_name='文章ID')),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Comment', verbose_name='评论的ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='评论者ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
