# Generated by Django 2.2.7 on 2019-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191128_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
