# Generated by Django 2.2.7 on 2019-11-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191128_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_last_updatetime',
            new_name='last_updatetime',
        ),
    ]
