# Generated by Django 2.2.7 on 2019-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20191129_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
