# Generated by Django 2.2.7 on 2019-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_article_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=200, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
